export const DASHBOARD_DATA_SOURCE_CONFIG = {
  opinetDiesel: {
    sourceCode: 'opinet-diesel',
    displayName: '오피넷',
    dataName: '전국 평균 자동차용경유 판매가격',
    dataCode: 'D047',
    providerName: '한국석유공사 오피넷',
    originalProviderName: null,
    unitLabel: '원/L',
    providerFrequencyLabel: '수집 파이프라인 기준',
    collectionFrequencyLabel: '자동 수집 작업 실행 시',
    purpose: '국내 경유 실제가격과 완료 주차 Actual 산정',
    description:
      '오피넷에서 제공하는 전국 평균 자동차용경유 판매가격을 국내 경유 실제가격과 완료 주차 Actual 산정에 사용합니다.',
    sourceUrl: 'https://www.opinet.co.kr/',
  },
  dubai: {
    sourceCode: 'opinet-dubai-daily',
    displayName: '두바이유',
    dataName: 'Dubai 현물가격 추정값',
    dataCode: 'Dubai',
    providerName: '한국석유공사 오피넷',
    originalProviderName: null,
    unitLabel: 'USD/BBL',
    providerFrequencyLabel: '일간(화~토 공개)',
    collectionFrequencyLabel: '자동 수집 작업 실행 시',
    purpose: '아시아 지역 국제 원유가격의 최신 일별 방향 참고',
    description:
      '싱가포르에서 거래된 Dubai 현물가격 추정값입니다. 실제 원천 관측일의 최신 유효 일별 값 두 건을 사용합니다.',
    sourceUrl: 'https://www.opinet.co.kr/glopcoilSelect.do',
  },
  usdKrw: {
    sourceCode: 'fred-usd-krw',
    displayName: 'USD/KRW',
    dataName: 'South Korean Won to U.S. Dollar Spot Exchange Rate',
    dataCode: 'DEXKOUS',
    providerName: 'FRED',
    originalProviderName: 'Board of Governors of the Federal Reserve System',
    unitLabel: '원/USD',
    providerFrequencyLabel: '일간(영업일)',
    collectionFrequencyLabel: '자동 수집 작업 실행 시',
    purpose: '달러 표시 원유가격의 원화 환산 영향 참고',
    description:
      'FRED DEXKOUS의 실제 원천 관측일 기준 최신 뉴욕 정오 매입환율 두 건으로 원/달러 환율 방향을 계산합니다.',
    sourceUrl: 'https://fred.stlouisfed.org/series/DEXKOUS',
  },
} as const;
