export const DASHBOARD_DATA_SOURCE_CONFIG = {
  opinetDiesel: {
    sourceCode: 'opinet-diesel',
    displayName: '오피넷',
    dataName: '전국 평균 자동차용경유 판매가격',
    dataCode: 'D047',
    providerName: '한국석유공사 오피넷',
    originalProviderName: null,
    unitLabel: '원/L',
    providerFrequencyLabel: '수집 파이프라인 기준',
    collectionFrequencyLabel: '자동 수집 작업 실행 시',
    purpose: '국내 경유 실제가격과 완료 주차 Actual 산정',
    description:
      '오피넷에서 제공하는 전국 평균 자동차용경유 판매가격을 국내 경유 실제가격과 완료 주차 Actual 산정에 사용합니다.',
    sourceUrl: 'https://www.opinet.co.kr/',
  },
  dubai: {
    sourceCode: 'opinet-dubai-daily',
    displayName: '두바이유',
    dataName: 'Dubai 현물가격 추정값',
    dataCode: 'Dubai',
    providerName: '한국석유공사 오피넷',
    originalProviderName: null,
    unitLabel: 'USD/BBL',
    providerFrequencyLabel: '일간(화~토 공개)',
    collectionFrequencyLabel: '자동 수집 작업 실행 시',
    purpose: '아시아 지역 국제 원유가격의 최신 일별 방향 참고',
    description:
      '싱가포르에서 거래된 Dubai 현물가격 추정값입니다. 실제 원천 관측일의 최신 유효 일별 값 두 건을 사용합니다.',
    sourceUrl: 'https://www.opinet.co.kr/glopcoilSelect.do',
  },
  usdKrw: {
    sourceCode: 'ecb-usd-krw',
    displayName: 'USD/KRW',
    dataName: 'ECB 일별 원/달러 기준환율',
    dataCode: 'EXR.D.KRW.EUR.SP00.A ÷ EXR.D.USD.EUR.SP00.A',
    providerName: '유럽중앙은행(ECB)',
    originalProviderName: null,
    unitLabel: '원/USD',
    providerFrequencyLabel: '일간(ECB 영업일)',
    collectionFrequencyLabel: '자동 수집 작업 실행 시',
    purpose: '달러 표시 원유가격의 원화 환산 영향 참고',
    description:
      'ECB가 영업일마다 고시하는 EUR 기준 USD·KRW 환율로 원/달러 교차환율을 계산하며, 최신 유효 일별 값 두 건으로 방향을 산출합니다.',
    sourceUrl: 'https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html',
  },
} as const;
